export async function searchMockHotels({
  destination = 'Lisboa',
  checkIn = '2026-10-12',
  checkOut = '2026-10-16',
  guests = 2,
  style = 'boutique premium',
} = {}) {
  return {
    status: 'mocked',
    provider: 'mock',
    query: { destination, checkIn, checkOut, guests, style },
    hotels: [
      {
        id: 'mock-hotel-memmo-alfama',
        name: 'Memmo Alfama',
        city: destination,
        neighborhood: 'Alfama',
        style: 'boutique central',
        nightlyRate: 1400,
        totalRate: 5600,
        currency: 'BRL',
        image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945',
        rating: 4.7,
        locationScore: 9.3,
        perks: ['café da manhã', 'upgrade sujeito à disponibilidade'],
        bestFor: 'localização',
        bookingUrl: 'https://voya.example/hotels/memmo-alfama',
        cancellationPolicy: 'Cancelamento flexível até 7 dias antes.',
      },
      {
        id: 'mock-hotel-bairro-alto',
        name: 'Bairro Alto Hotel',
        city: destination,
        neighborhood: 'Bairro Alto',
        style: 'editorial premium',
        nightlyRate: 1650,
        totalRate: 6600,
        currency: 'BRL',
        image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa',
        rating: 4.8,
        locationScore: 9.5,
        perks: ['late checkout', 'crédito de restaurante'],
        bestFor: 'serviço',
        bookingUrl: 'https://voya.example/hotels/bairro-alto',
        cancellationPolicy: 'Cancelamento com reembolso parcial após confirmação.',
      },
      {
        id: 'mock-hotel-family-lisboa',
        name: 'Lisboa Family Suites',
        city: destination,
        neighborhood: 'Baixa',
        style: 'apart-hotel familiar',
        nightlyRate: 1180,
        totalRate: 4720,
        currency: 'BRL',
        image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791',
        rating: 4.5,
        locationScore: 8.9,
        perks: ['quarto família', 'cozinha compacta', 'lavanderia'],
        bestFor: 'família',
        bookingUrl: 'https://voya.example/hotels/lisboa-family-suites',
        cancellationPolicy: 'Cancelamento grátis até 5 dias antes.',
      },
    ],
  };
}
