export const expertKnowledgeSeed = [
  {
    expertName: 'Esteban Pelo Mundo',
    destination: 'Orlando',
    category: 'parques',
    insight: 'Em viagem com crianças, intercale parque intenso com manhã mais lenta ou dia de piscina.',
    reason: 'O descanso planejado reduz irritação, melhora o aproveitamento dos parques e evita excesso de deslocamento.',
    applicableTo: ['família', 'crianças', 'ritmo leve', 'Disney'],
    confidence: 0.92,
    tags: ['orlando', 'disney', 'criancas', 'descanso', 'parques'],
  },
  {
    expertName: 'Status Viajante',
    destination: 'Lisboa',
    category: 'custo-benefício',
    insight: 'Em Lisboa, hotel bem localizado costuma economizar mais tempo e energia do que uma diária levemente mais barata fora do centro.',
    reason: 'A economia aparente pode virar mais deslocamento, mais transporte e menos flexibilidade no roteiro.',
    applicableTo: ['casal', 'família', 'orçamento controlado', 'ritmo leve'],
    confidence: 0.9,
    tags: ['lisboa', 'hotel', 'localizacao', 'custo-beneficio', 'logistica'],
  },
  {
    expertName: 'Jaime Drummond',
    destination: 'Lisboa',
    category: 'experiências memoráveis',
    insight: 'Combine uma experiência cultural curta com uma reserva gastronômica especial em vez de empilhar muitas atividades no mesmo dia.',
    reason: 'A viagem fica mais autoral e menos cansativa, com mais chance de criar memória real.',
    applicableTo: ['Europa', 'cultura', 'gastronomia', 'ritmo equilibrado'],
    confidence: 0.89,
    tags: ['lisboa', 'cultura', 'gastronomia', 'experiencias', 'memoria'],
  },
  {
    expertName: 'Curadoria interna',
    destination: 'Qualquer destino',
    category: 'orçamento',
    insight: 'Quando o orçamento estiver apertado, preserve o voo mais eficiente e ajuste hotel ou experiências antes de aceitar uma conexão ruim.',
    reason: 'O cansaço do deslocamento costuma contaminar vários dias da viagem.',
    applicableTo: ['orçamento controlado', 'família', 'ritmo leve', 'milhas'],
    confidence: 0.87,
    tags: ['orcamento', 'voos', 'conexao', 'milhas', 'estrategia'],
  },
];
