export async function searchMockFlights({
  origin = 'GRU',
  destination = 'LIS',
  date = '2026-10-12',
  travelers = 2,
  cabin = 'executiva',
} = {}) {
  return {
    status: 'mocked',
    provider: 'mock',
    query: { origin, destination, date, travelers, cabin },
    flights: [
      {
        id: 'mock-flight-tap-088',
        airline: 'TAP',
        flightNumber: 'TP 088',
        origin,
        destination,
        departureTime: '2026-10-12T23:15:00-03:00',
        arrivalTime: '2026-10-13T12:55:00+01:00',
        durationMinutes: 640,
        stops: 0,
        stopoverInfo: 'Direto',
        price: 4820,
        currency: 'BRL',
        milesPrice: '78.000 TAP + R$ 240',
        walletBenefits: ['sala VIP Star Alliance', 'embarque prioritário', 'seguro viagem'],
        baggageIncluded: '2 malas despachadas',
        familyScore: 9,
        comfortScore: 8,
        bookingUrl: 'https://voya.example/flights/tap-088',
        recommendationReason: 'Voo direto, menor desgaste e bom uso de milhas TAP.',
        confidence: 0.92,
        cabin,
      },
      {
        id: 'mock-flight-latam-8084',
        airline: 'LATAM',
        flightNumber: 'LA 8084',
        origin,
        destination,
        departureTime: '2026-10-12T20:05:00-03:00',
        arrivalTime: '2026-10-13T16:45:00+01:00',
        durationMinutes: 880,
        stops: 1,
        stopoverInfo: '1 conexão em Madri, 2h10',
        price: 3980,
        currency: 'BRL',
        milesPrice: '92.000 Latam Pass',
        walletBenefits: ['acúmulo Latam Pass', 'bagagem conforme tarifa'],
        baggageIncluded: '1 mala despachada',
        familyScore: 6,
        comfortScore: 6,
        bookingUrl: 'https://voya.example/flights/latam-8084',
        recommendationReason: 'Melhor tarifa, mas com conexão e maior duração.',
        confidence: 0.84,
        cabin,
      },
      {
        id: 'mock-flight-iberia-6824',
        airline: 'Iberia',
        flightNumber: 'IB 6824',
        origin,
        destination,
        departureTime: '2026-10-12T15:25:00-03:00',
        arrivalTime: '2026-10-13T09:40:00+01:00',
        durationMinutes: 735,
        stops: 1,
        stopoverInfo: '1 conexão em Madri, 1h05',
        price: 4320,
        currency: 'BRL',
        milesPrice: '85.000 Avios + taxas',
        walletBenefits: ['possível lounge oneworld', 'acúmulo Avios'],
        baggageIncluded: '1 mala despachada',
        familyScore: 5,
        comfortScore: 7,
        bookingUrl: 'https://voya.example/flights/iberia-6824',
        recommendationReason: 'Boa cabine, mas conexão curta aumenta risco para família.',
        confidence: 0.78,
        cabin,
      },
    ],
  };
}
